### ISSUE TITLE
Using simpler-wick with braket package

### ISSUE THREAD

**Issue by matthewfeickert** [JP-Ellis/simpler-wick#2]
Do you know of a way to use simpler-wick with the [braket package](https://www.ctan.org/pkg/braket?lang=en)?

As an example of what I mean, this works
`\[
\wick{\c {\left< A\right|} \c A \left|B\right>}
\]`
but this doesn't
`\[
\wick{\Braket{\c A|\c A|B}}
\]`

**Comment by JP-Ellis** [comment]
I don't use the braket package as I have written something of my own to handles brakets (not a CTAN); however, I've had a look at fixing it, and it looks like it works now:

```tex
\(
\displaystyle
  \wick[offset=1.5em]{\Braket{\c \phi | \frac{x}{y} | \c \phi}}
  \wick[offset=1.5em]{\Braket{\c1 \phi | \frac{x}{y} | \c2\rho} \Braket{\c2 \rho |
      \frac{y}{z} | \c1 \phi}}
\)
```
<p align="center"><img src="https://cloud.githubusercontent.com/assets/3196162/12693125/32f57990-c756-11e5-9060-473bf0512f03.png" width="347px"></p>

Could you download the [`simpler-wick.sty`](https://github.com/JP-Ellis/simpler-wick/blob/braket-compatibility/simpler-wick.sty) file from the [`braket-compatibility`](https://github.com/JP-Ellis/simpler-wick/tree/braket-compatibility) branch, place it in the same directory as your TeX file and let me know if it fixes the issue for you too?  I'll then merge this change into the master branch and update the version on CTAN once.

**Comment by matthewfeickert** [comment]
Sorry, I'm currently getting an error for that. I've attached the log and output files for `xelatex wick_test.tex`
[wick_test.log.txt](https://github.com/JP-Ellis/simpler-wick/files/121033/wick_test.log.txt)
[wick_test.out.log.txt](https://github.com/JP-Ellis/simpler-wick/files/121034/wick_test.out.log.txt)

**Comment by JP-Ellis** [comment]
When you download the file, make sure that you download the raw file and not the HTML file.  The error message in the log explain what's going on:

```text
! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.5 <
     !DOCTYPE html>
? 
! You can't use `macro parameter character #' in horizontal mode.
l.7   <head prefix="og: http://ogp.me/ns#
                                          fb: http://ogp.me/ns/fb# object: h...

? 
! You can't use `macro parameter character #' in horizontal mode.
```

You can get the raw file by clicking the `raw` button in the link I gave above, or here's the direct link: https://raw.githubusercontent.com/JP-Ellis/simpler-wick/braket-compatibility/simpler-wick.sty

**Comment by matthewfeickert** [comment]
Derp! Sorry, that was dumb!

Everything is good to go now, and yes, the simpler-wick.sty file from the braket-compatibility branch works perfectly find with the braket pacakge now.

Many thanks, Joshua!

**Comment by JP-Ellis** [comment]
I'm glad it is all resolved.  I'll update the master branch and the version on CTAN soon.

**Comment by melsophos** [comment]
I am adding a small comment on this topic: I think this fixes more generally the case where one \c appears inside something, which is very frequent. In my case it solves the problem for my definition of the normal ordering with `:\mathrel{#1}:` which ensures that the colons are correctly placed. Would it be possible to update the package on CTAN since it seems to me to be a major feature? (And hopefully this will be reflected in the Linux packages.)

**Comment by zhyiyu** [comment]
This seems not working for me, the Wick contraction is not showing up.
